# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seotools', '0004_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metatags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_uri', models.CharField(default='', max_length=128)),
                ('title_text', models.CharField(max_length=128)),
                ('description_text', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
