# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seotools', '0006_auto_20170505_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metatags',
            name='description_text',
        ),
    ]
