# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seotools', '0007_remove_metatags_description_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatags',
            name='description_text',
            field=models.CharField(default='', max_length=256),
        ),
    ]
